apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  ports:
  - name: "vote-service"
    port: 8080         # Exposed port for the service
    nodePort: 31000    # NodePort is not typically needed in LoadBalancer, but it can still be included
  selector:
    app: vote
