apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  ports:
  - name: "result-service"
    protocol: TCP
    port: 8081         # Exposed port for the service externally
    targetPort: 80     # Port on the pod that the service forwards traffic to
  selector:
    app: result
