apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    protocol: TCP
    port: 8081
    targetPort: 80
    # nodePort: 31001
  selector:
    app: result



